

SELECT * FROM CLIENT;
SELECT * FROM TYPTRX;
SELECT * FROM COMMODITE;
SELECT * FROM TYPECHAM;
SELECT * FROM LOCALISATION;
SELECT * FROM RESERVATION;

SELECT * FROM RESERVATION;

SELECT CURRENT_DATE FROM dual;